version: '3'
services:
  web:
    image: docker.pkg.github.com/chickaree/web/web
    restart: always
    networks:
      - default
      - ingress
    environment:
      VIRTUAL_HOST: 'chickar.ee,origin.chickar.ee'
      LETSENCRYPT_HOST: 'chickar.ee,origin.chickar.ee'
networks:
  ingress:
    external:
      name: ingress
